### ISSUE TITLE
文章页无法获取图库图片

### ISSUE THREAD

**Issue by mcrwayfun** [flute/skywalker#14]
环境：
- centos：7.4
- nginx：1.14

问题：无法获取图片，报**No 'Access-Control-Allow-Origin' header is present on the requested resource**错误。已经在nginx的中添加如下配置：
```
location / {
     add_header Access-Control-Allow-Origin *;
     ...
}
```
能解答一下么，谢谢！

**Comment by FengHelloWorld** [comment]
求我就告诉你！

**Comment by flute** [comment]
之前图片接口没有对外开放，现在已开放。
