### ISSUE TITLE
有个默认的图，然后会把它刷掉，开一次网页闪两张图

### ISSUE THREAD

**Issue by txcjhaz** [flute/skywalker#16]

**Comment by flute** [comment]
目前做法是：  设置一张默认背景，加载网页时请求获取bing图片，请求成功时覆盖默认图片。
设置默认背景考虑两点：
1.  bing图片获取可能会失败，导致背景空白。
2. bing图片尺寸较大，获取时间较长，如果没有默认背景，会导致有一段时间的空白。

如果想去掉网页闪烁，在代码中将默认的背景图去掉即可。
