### ISSUE TITLE
使用主题的时候报错，希望能修复一下

### ISSUE THREAD

**Issue by Lucifer11111** [flute/skywalker#6]
Activation failed
Fatal Errors
(Must-fix to activate theme)

The {{image}} helper was replaced with the {{img_url}} helper. Please read the details..
Replace the {{@blog.cover}} helper with {{@blog.cover_image}}
Replace the {{#if image}} helper with {{#if feature_image}}, or {{#if profile_image}}

ghost版本是1.21.5

按照提示改了，重启后，样式都没有了

**Comment by flute** [comment]
最新版本已兼容ghost 1.x版本。
